apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: firefly
  namespace: firefly
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - firefly.k8s.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: firefly
          port: 8080
