# EXAMPLE SECRETS - DO NOT COMMIT REAL VALUES
# Copy this file and create actual secrets with real values
#
# To create the secrets:
#   kubectl create secret generic firefly-secret -n firefly \
#     --from-literal=DATABASE_URL='postgresql://firefly:your-password@postgres.firefly.svc.cluster.local:5432/firefly' \
#     --from-literal=SECRET_KEY='your-jwt-secret-key-min-32-chars' \
#     --from-literal=GITHUB_CLIENT_ID='your-github-oauth-client-id' \
#     --from-literal=GITHUB_CLIENT_SECRET='your-github-oauth-client-secret'
#
#   kubectl create secret generic postgres-secret -n firefly \
#     --from-literal=POSTGRES_USER='firefly' \
#     --from-literal=POSTGRES_PASSWORD='your-password' \
#     --from-literal=POSTGRES_DB='firefly'
---
apiVersion: v1
kind: Secret
metadata:
  name: firefly-secret
  namespace: firefly
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://firefly:CHANGE_ME@postgres.firefly.svc.cluster.local:5432/firefly'
  SECRET_KEY: 'CHANGE_ME_TO_A_LONG_RANDOM_STRING_32_CHARS'
  GITHUB_CLIENT_ID: 'CHANGE_ME'
  GITHUB_CLIENT_SECRET: 'CHANGE_ME'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: firefly
type: Opaque
stringData:
  POSTGRES_USER: 'firefly'
  POSTGRES_PASSWORD: 'CHANGE_ME'
  POSTGRES_DB: 'firefly'
