apiVersion: v1
kind: ServiceAccount
metadata:
  name: firefly
  namespace: firefly
  labels:
    app: firefly
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: firefly
  labels:
    app: postgres
